apiVersion: v1
kind: Namespace
metadata:
  name: ml-serving
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: timeseries-lstm
  namespace: ml-serving
  annotations:
    serving.kserve.io/deploymentMode: Knative
spec:
  predictor:
    minReplicas: 0
    maxReplicas: 2
    containers:
      - name: kserve-container
        image: docker.io/library/timeseries-lstm-serving:v2
        imagePullPolicy: Never
        ports:
          - containerPort: 8080
            protocol: TCP
        env:
          - name: MODEL_NAME
            value: timeseries-lstm
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: "1"
            memory: 768Mi
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 2
