ClusterName=mlops-lab

SlurmctldHost=slurm-controller(192.168.56.20)

SlurmUser=slurm
SlurmdUser=root

AuthType=auth/munge

StateSaveLocation=/var/spool/slurmctld
SlurmdSpoolDir=/var/spool/slurmd

SlurmctldPidFile=/run/slurmctld.pid
SlurmdPidFile=/run/slurmd.pid

SlurmctldPort=6817
SlurmdPort=6818

ProctrackType=proctrack/linuxproc
TaskPlugin=task/affinity

ReturnToService=2

SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core_Memory

InactiveLimit=0
KillWait=30
MinJobAge=300
SlurmctldTimeout=120
SlurmdTimeout=300
WaitTime=0

NodeName=slurm-compute01 \
  NodeAddr=192.168.56.21 \
  CPUs=2 \
  Boards=1 \
  SocketsPerBoard=1 \
  CoresPerSocket=2 \
  ThreadsPerCore=1 \
  RealMemory=1900 \
  State=UNKNOWN

NodeName=slurm-compute02 \
  NodeAddr=192.168.56.22 \
  CPUs=2 \
  Boards=1 \
  SocketsPerBoard=1 \
  CoresPerSocket=2 \
  ThreadsPerCore=1 \
  RealMemory=1900 \
  State=UNKNOWN

PartitionName=cpu \
  Nodes=slurm-compute[01-02] \
  Default=YES \
  MaxTime=INFINITE \
  State=UP
